name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main # Change this to your main branch

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: npm run build # Adjust this command based on your build process

            - name: Configure Git
              run: |
                  git config --global user.name "maximlamare"
                  git config --global user.email "32132761+maximlamare@users.noreply.github.com"

            - name: Deploy to GitHub Pages
              run: |
                  git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
                  npx gh-pages -d build --user "maximlamare <32132761+maximlamare@users.noreply.github.com>" --message "Deploying to GitHub Pages"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Set the GitHub token for authentication
