# Run tests
name: CI - run unit tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Yarn test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install Yarn
      - name: Install Yarn
        run: npm install --global yarn

      # Cache Yarn dependencies to speed up subsequent builds
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
              ${{ runner.os }}-yarn-

      # Install Yarn dependencies
      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: |
          yarn test --coverage
  
